In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/manal/OneDrive/Desktop/Job Market Analytics/data/job_market_analytics.csv")

In [2]:
df = df.drop_duplicates()
df.shape

(100000, 20)

In [23]:
df.head()

,job_id,job_title,company_name,industry,company_size,city,country,region,experience_level,employment_type,...,education,applicants,views,posted_date,skills,description,status,salary_avg,posted_year,posted_month
0,1,Data Analyst,Capgemini,Education,51-200,Casablanca,Morocco,Africa,Junior,Full-time,...,Master,35,1981,2026-07-15,"Python, SQL",Job description,Closed,96500.0,2026,7
1,2,Analytics Engineer,Google,Technology,51-200,Dubai,UAE,Asia,Junior,Full-time,...,Master,73,4439,2026-06-21,"Python, SQL",Job description,Closed,86000.0,2026,6
2,3,Data Engineer,Orange,Education,1-50,Montreal,Canada,North America,Senior,Full-time,...,PhD,272,3512,2026-02-21,"SQL, Tableau",Job description,Closed,73500.0,2026,2
3,4,Data Scientist,CGI,Education,1000+,Berlin,Germany,Europe,Mid,Internship,...,PhD,37,977,2020-12-01,"SQL, dbt",Job description,Closed,60500.0,2020,12
4,5,ML Engineer,Amazon,Healthcare,201-1000,Madrid,Spain,Europe,Senior,Internship,...,Master,35,776,2026-04-04,"SQL, Tableau",Job description,Closed,50500.0,2026,4

In [24]:
df.shape

(100000, 23)

In [ ]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_id            100000 non-null  int64
 1   job_title         100000 non-null  str
 2   company_name      100000 non-null  str
 3   industry          100000 non-null  str
 4   company_size      100000 non-null  str
 5   city              100000 non-null  str
 6   country           100000 non-null  str
 7   region            100000 non-null  str
 8   experience_level  100000 non-null  str
 9   employment_type   100000 non-null  str
 10  remote_type       100000 non-null  str
 11  salary_min        100000 non-null  float64
 12  salary_max        100000 non-null  int64
 13  education         100000 non-null  str
 14  applicants        100000 non-null  int64
 15  views             100000 non-null  int64
 16  posted_date       100000 non-null  datetime64[us]
 17  skills            100000 non-null  str
 18  description       100000 non-null  str
 19  status            100000 non-null  str
 20  salary_avg        100000 non-null  float64
 21  posted_year       100000 non-null  int32
 22  posted_month      100000 non-null  int32
dtypes: datetime64[us](1), float64(2), int32(2), int64(4), str(14)
memory usage: 27.6 MB

,job_id,job_title,company_name,industry,company_size,city,country,region,experience_level,employment_type,...,education,applicants,views,posted_date,skills,description,status,salary_avg,posted_year,posted_month
0,1,Data Analyst,Capgemini,Education,51-200,Casablanca,Morocco,Africa,Junior,Full-time,...,Master,35,1981,2026-07-15,"Python, SQL",Job description,Closed,96500.0,2026,7
1,2,Analytics Engineer,Google,Technology,51-200,Dubai,UAE,Asia,Junior,Full-time,...,Master,73,4439,2026-06-21,"Python, SQL",Job description,Closed,86000.0,2026,6
2,3,Data Engineer,Orange,Education,1-50,Montreal,Canada,North America,Senior,Full-time,...,PhD,272,3512,2026-02-21,"SQL, Tableau",Job description,Closed,73500.0,2026,2
3,4,Data Scientist,CGI,Education,1000+,Berlin,Germany,Europe,Mid,Internship,...,PhD,37,977,2020-12-01,"SQL, dbt",Job description,Closed,60500.0,2020,12
4,5,ML Engineer,Amazon,Healthcare,201-1000,Madrid,Spain,Europe,Senior,Internship,...,Master,35,776,2026-04-04,"SQL, Tableau",Job description,Closed,50500.0,2026,4

In [26]:
df.describe()

,job_id,salary_min,salary_max,applicants,views,posted_date,salary_avg,posted_year,posted_month
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000,100000.00000,100000.000000,100000.000000
mean,50000.500000,59518.760000,76487.990000,250.133390,2512.521190,2023-04-12 09:10:26.399999,68003.37500,2022.796650,6.306410
min,1.000000,30000.000000,25000.000000,0.000000,10.000000,2020-01-01 00:00:00,27500.00000,2020.000000,1.000000
25%,25000.750000,45000.000000,61000.000000,125.000000,1262.750000,2021-08-18 00:00:00,53000.00000,2021.000000,3.000000
50%,50000.500000,60000.000000,76000.000000,250.000000,2519.000000,2023-04-10 00:00:00,68000.00000,2023.000000,6.000000
75%,75000.250000,74000.000000,92000.000000,375.000000,3760.000000,2024-12-05 00:00:00,83000.00000,2024.000000,9.000000
max,100000.000000,89000.000000,128000.000000,500.000000,5000.000000,2026-07-28 00:00:00,108500.00000,2026.000000,12.000000
std,28867.657797,17131.359634,21621.356817,144.716338,1440.521762,NaN,18354.96895,1.907599,3.415904

In [31]:
df.columns

Index(['job_id', 'job_title', 'company_name', 'industry', 'company_size',
       'city', 'country', 'region', 'experience_level', 'employment_type',
       'remote_type', 'salary_min', 'salary_max', 'education', 'applicants',
       'views', 'posted_date', 'skills', 'description', 'status', 'salary_avg',
       'posted_year', 'posted_month'],
      dtype='str')

In [32]:
df.isnull().sum()

job_id              0
job_title           0
company_name        0
industry            0
company_size        0
city                0
country             0
region              0
experience_level    0
employment_type     0
remote_type         0
salary_min          0
salary_max          0
education           0
applicants          0
views               0
posted_date         0
skills              0
description         0
status              0
salary_avg          0
posted_year         0
posted_month        0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.nunique()

job_id              100000
job_title                8
company_name            20
industry                 6
company_size             4
city                    12
country                  6
region                   4
experience_level         3
employment_type          3
remote_type              3
salary_min              60
salary_max             104
education                3
applicants             501
views                 4991
posted_date           2401
skills                   6
description              1
status                   2
salary_avg             163
posted_year              7
posted_month            12
dtype: int64

In [5]:
df["salary_min"].median()
df["salary_min"] = df["salary_min"].fillna(df["salary_min"].median())
df.isnull().sum()

job_id              0
job_title           0
company_name        0
industry            0
company_size        0
city                0
country             0
region              0
experience_level    0
employment_type     0
remote_type         0
salary_min          0
salary_max          0
education           0
applicants          0
views               0
posted_date         0
skills              0
description         0
status              0
dtype: int64

In [7]:
df["posted_date"] = pd.to_datetime(df["posted_date"])
df["posted_date"].dtype

dtype('<M8[us]')

In [11]:
df["employment_type"] = df["employment_type"].replace({
    "Full time": "Full-time"
})
df["employment_type"].value_counts()

employment_type
Full-time     50102
Contract      24958
Internship    24940
Name: count, dtype: int64

In [12]:
df["salary_avg"] = (df["salary_min"] + df["salary_max"]) / 2
df[["salary_min", "salary_max", "salary_avg"]].head()

   salary_min  salary_max  salary_avg
0     82000.0      111000     96500.0
1     70000.0      102000     86000.0
2     70000.0       77000     73500.0
3     41000.0       80000     60500.0
4     32000.0       69000     50500.0

In [15]:
df["posted_year"] = df["posted_date"].dt.year
df["posted_month"] = df["posted_date"].dt.month
df[["posted_date", "posted_year"]].head()
df[["posted_date", "posted_month"]].head()

  posted_date  posted_month
0  2026-07-15             7
1  2026-06-21             6
2  2026-02-21             2
3  2020-12-01            12
4  2026-04-04             4

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   job_id            100000 non-null  int64
 1   job_title         100000 non-null  str
 2   company_name      100000 non-null  str
 3   industry          100000 non-null  str
 4   company_size      100000 non-null  str
 5   city              100000 non-null  str
 6   country           100000 non-null  str
 7   region            100000 non-null  str
 8   experience_level  100000 non-null  str
 9   employment_type   100000 non-null  str
 10  remote_type       100000 non-null  str
 11  salary_min        100000 non-null  float64
 12  salary_max        100000 non-null  int64
 13  education         100000 non-null  str
 14  applicants        100000 non-null  int64
 15  views             100000 non-null  int64
 16  posted_date       100000 non-null  datetime64[us]
 17  skills            100000 non-null  str
 18  description       100000 non-null  str
 19  status            100000 non-null  str
 20  salary_avg        100000 non-null  float64
 21  posted_year       100000 non-null  int32
 22  posted_month      100000 non-null  int32
dtypes: datetime64[us](1), float64(2), int32(2), int64(4), str(14)
memory usage: 27.6 MB

In [22]:
df.to_csv(
    r"C:\Users\manal\OneDrive\Desktop\Job Market Analytics\data\job_market_cleaned.csv",
    index=False
)